server:
  port : 9000

spring:
  application:
    name: gateway-service  
  cloud:
    gateway:
      routes:
      - id: baeldung
        uri: 'http://localhost:8080/helpdesk'
        predicates:
        - Path=/helpdesk/**
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        